spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imperator?false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=FALSE
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
  mail:
    host: smtp.qq.com
    username: 1342878298@qq.com
    password:
    default-encoding: UTF-8
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    database: 0
    password:
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.starrier.imperator.content.entity
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
