spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imperator?false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=FALSE
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
  mail:
    host: smtp.qq.com
    username: 1342878298@qq.com
    password:
    default-encoding: UTF-8
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    database: 0
    password:
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.starrier.imperator.content.entity
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
rocketmq:
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: imperator
    #mq的nameserver地址
    namesrvAddr: 127.0.0.1:9876
    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: imperator-content
    #topic名称
    topic: TEST
    #根据实际情况设置消息的tag
    tag: first
    #消息最大长度
    maxMessageSize: 131072 # 1024*128
    #发送消息超时时间
    sendMsgTimeout: 10000
  consumer:
    namesrvAddr: 127.0.0.1:9876
    groupName: imperator
    topic: TEST
    tag: first
    consumeThreadMin: 20
    consumeThreadMax: 64
