global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10m
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /monitoring/actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - localhost: 9902